### PR TITLE
Fix the issue the loading spinner is always spinning

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**

### CODE REVIEW

**Review by mollux — DISMISSED** [review]
this fixes the save button (and some unrelated issues)

**Comment by mollux** [comment]
@volha-pivavarchyk we can merge this into the main branch I think? as it's not related to ckeditor5?

**Comment by mollux** [comment]
@volha-pivavarchyk I would commit the generated files for now, I don't see a workflow here that builds them


We can look into a better flow once M5 is released :)

**Comment by volha-pivavarchyk** [comment]
@mollux I added the dist files. Now I know that they should be added :)

I think it can be merged into main. I chose the checkeditor5 branch as this branch was used in PR #44.

**Review by LordRembo — APPROVED** [review]

**Comment by LordRembo** [comment]
- Checked out the plugin,
- copied it into Mautic's grapesjs builder bundle
-  rebuilt the bundle
- saved an email
- got a notification of successful save

notification-spinner

**Review by LordRembo — APPROVED** [review]

**Review by mollux — APPROVED** [review]

**Pull request merged**
