### PR TITLE
Adjustments for refactoring mautic plugin

### PR DESCRIPTION
**Pull request by adiux**
I used the same coding style and linter rules as with the plugin. So we have consistency there. In addition, I added a couple of changes related to dynamic content and the "mode detection": html vs mjml.

These changes were necessary after I switched to the so-called "modern" import style.

### CODE REVIEW

**Comment by dennisameling** [comment]
@adiux I [just added](https://github.com/mautic/grapesjs-preset-mautic/pull/1/commits/d8f4bccfa9187e09ad9ea587279481a1cdb56da6) a basic GitHub Actions workflow to your PR, so that the Prettier checks will run automatically on PRs and commits in this repo. However, it will only be activated after this PR has been merged 😅 

Running it locally looks good:

```
$ npm run prettier-check

> grapesjs-preset-mautic@1.0.0 prettier-check /home/dennis/repos/grapesjs-preset-mautic
> prettier -c src/

Checking formatting...
All matched files use Prettier code style!
```

**Comment by adiux** [comment]
Thanks @dennisameling! Thats great!

**Comment by RCheesley** [comment]
@adiux how can we go about testing this?

**Comment by RCheesley** [comment]
@dennisameling would you be OK with the code from a code review standpoint or were you just implementing the workflows?

If so then we are good to merge, if not we need to find someone to review!

**Review by dennisameling — COMMENTED** [review]
I only added the workflow indeed. From a code perspective, the code that the linter changed looks good, but I haven't tested the changes done in https://github.com/mautic/grapesjs-preset-mautic/pull/1/commits/7c9775b6950c00a490d9dd78a5b0bdeecc1d5b81. Would need someone to actually works as intended there 😊 atm I can't think of a reason why it wouldn't work just looking at the code, but I've proved myself wrong in the past 😉

**Comment by adiux** [comment]
thanks @dennisameling for checking. The corresponding code is here in the plugin: https://github.com/adiux/plugin-grapesjs-builder/blob/refactor-to-service-with-linting-and-fixes/Assets/library/js/builder.service.js#L206

**Pull request merged**
