### PR TITLE
Update grapesjs compatibility (Mautic 5)

### PR DESCRIPTION
**Pull request by LordRembo**
Registering your custom components using the legacy method breaks when updating GrapesJS to [release 0.20.1](https://github.com/GrapesJS/grapesjs/releases/tag/v0.20.1). Need this to be able to upgrade GrapesJS in the GrapesJSBuilderBundle.

[Here is a PR for Mautic 4](https://github.com/mautic/grapesjs-preset-mautic/pull/50)

To test:
* have a Mautic 5.x running locally
* replace the package with my forked branch in plugins/GrapesJsBuilderBundle, eg. by running `npm i grapesjs-preset- mautic@github:LordRembo/grapesjs-preset-mautic#update-grapesjs-m5` inside that bundle
* rebuilding GrapesJs bundle by running `npm run build`
* Make or edit an email and see that you can still use drag & drop to add/move/edit a Dynamic content Block.
* Check that there are no new JS errors
* You should still be able to save that edited mail

### CODE REVIEW

**Comment by LordRembo** [comment]
It would be helpful if someone testing this, can put special attention to any JS errors in GrapesJs and if there are any unexpected font differences with the 5.x branch.

**Comment by LordRembo** [comment]
About the changes:
* The code changes outside the dist folder were done by hand, the rest is done by running the build script
* The most important change is, [some syntax that was already deprecated becomes invalid when updating to GrapesJs 0.21.1](https://github.com/GrapesJS/grapesjs/releases#:~:text=Compare-,v0.21.1,-%E2%9A%A0%EF%B8%8F) so I replaced that
* I had to make a second change, and that is to check for the 'options' property if 'list' doesn't exist, when checking the list of fonts in the Editor. 'options' is how it is listed in the documentation of current GrapesJs, I think 'list' is older syntax perhaps. In any case, I made both possible now.

**Review by patrykgruszka — COMMENTED** [review]
The code updates seem good. But I can't check the mail builder because there's an issue with the 5.x branch: https://github.com/mautic/mautic/issues/13510.

**Comment by RCheesley** [comment]
I think the description should maybe say you need a local copy of 5.x rather than 4.x?

**Comment by LordRembo** [comment]
@RCheesley ah, right, sorry. Changed it.

**Comment by LordRembo** [comment]
I've added a few new changes to fix issues with icons (as noted in [the PR this is a dependency for](https://github.com/mautic/mautic/pull/13283)).
Downside is that this means this won't be perfectly backwards compatible anymore with non-updated GrapesJS. So this dependency should be merged, [alongside this PR](https://github.com/mautic/mautic/pull/13283);

**Comment by patrykgruszka** [comment]
There is a different between how the dynamic content is displayed between versions 5.0.3 and after this update:
This PR:
image

5.0.3:
image

There's an existing issue where the textarea multiplies for dynamic content, but this problem also exists on 5.0.3 version. Adding multiple dynamic content blocks leads to duplicated textareas.
image

**Comment by LordRembo** [comment]
@patrykgruszka Thanks for catching this issue! I'll give it a look, see what I come up with. I'll ignore the duplication of text areas for now. Maybe you could open a new issue for that specific problem, if there isn't one already?

**Comment by LordRembo** [comment]
It looks a bit like the Dynamic Content block is simply not properly rendered (shows the `mj-text` tag but should render a table row and cell with the same attributes).
Looking in `src/dynamicContent/dynamicContent.domcomponents.js` and related files to see how the component is built up, there doesn't seem to be anything major broken. A couple of things I can tweak that was already wrong in the original (eg. `isComponent` check should be moved 'cause it doesn't trigger here, some other checks that could be better) but they don't seem to be the root cause of the render issue.
Will try finding time to look at it a bit deeper next week.

**Comment by LordRembo** [comment]
@adiux I see that you have worked extensively on the Dynamic content block. I could use a bit of help figuring out why this is broken, all of a sudden: 

- the output is all of a sudden no longer rendered as a tr/td but just an `mj-text` tag
- any added Dynamic content blocks are no longer stored. You can't edit them anymore after closing and reopening a mail (`No Dynamic Content editor found for decId` )

All I updated for it, was change the use of the legacy API with the new one ([as per these release notes](https://github.com/GrapesJS/grapesjs/releases/tag/v0.20.1)) but I don't understand enough about the Dynamic content block to see where/why these issues occur.  
I've cleaned up the code here and there, hoping to find some syntax issues but that doesn't seem to be the case.

**Comment by adiux** [comment]
Hi @LordRembo as far as I understand it the DC is stored in the DOM (#dynamicContentContainer) of the editor pages HTML. The decId is used to link it to a DC editor (where you actually edit the DC). The `data-param-dec-id` is persisted to the db and can be used to link to the item store in the html. The store id starts with 0. So decId is always + 1. 

There is a GJS command that transforms the token ({dynamiccontent="Dynamic Content 2"}) to the representation in the UI.

Not sure why there is only mj-text, but I would start fixing this error. Hope this helps. Let me know if you have questions.

**Comment by LordRembo** [comment]
@adiux Seems like the 'remove' event is fired whenever the Builder is opened, and that removes the item. That should not be the case I think? You have any idea if this code can be safely removed?

```
  // @todo merge events and listeners. or move this to the component itself as a
  // local listener. see create-new-dynamic-content-store-item
  onComponentRemove() {
    this.editor.on('component:remove', (component) => {
      // Delete dynamic-content on Mautic side
      if (component.get('type') === 'dynamic-content') {
        console.debug('dynamic content remove');
        this.editor.runCommand('preset-mautic:dynamic-content-delete-store-item', { component });
      }
    });
  }
```

**Comment by adiux** [comment]
@LordRembo just from this snipped, this seems to be needed. Otherwise, how would a DC be removed?

Why is it fired on the opening of the builder. That sounds strange to me.

**Comment by LordRembo** [comment]
@adiux Without it, the blocks do get removed in code but it's only an empty reference that is kept in storage. Which I would agree is at least good practice to clean up.  
I figured out the problem over the weekend: there's an extra condition needed to make sure only the block that is selected for removal, is actually removed. Doesn't make any sense that this isn't filtered beforehand but that's GrapesJS I guess. Found references to this in a GrapesJS ticket from 2022.

**Comment by LordRembo** [comment]
Alright, issues fixed, updated [the grapesjs update PR](https://github.com/mautic/mautic/pull/13283) to use the latest changes. Refer to that one for QA.

**Comment by LordRembo** [comment]
Incidentally, that last fix I added, is also a fix for this issue: https://github.com/mautic/grapesjs-preset-mautic/issues/48

**Comment by LordRembo** [comment]
Just practically, I think we need a 5.1 branch to merge this thing, because it is used for [the GrapesJS upgrade PR](https://github.com/mautic/mautic/pull/13283) and that one is planned for a 5.1 release.
@escopecz or @mollux Do you think this is a good solution? If so, maybe one of you could make one?

**Comment by escopecz** [comment]
I created the 5.1 branch

**Comment by LordRembo** [comment]
Alright! [The PR that depends on this update](https://github.com/mautic/mautic/pull/13283), has its required 2 approval reviews. So this preset should be good to merge (against the 5.1 branch).
Afterwards, I'll update the reference in that other PR.

**Pull request merged**
