### PR TITLE
Fix: Allow no doctype (null) and add html tag to html emails and landingpage

### PR DESCRIPTION
**Pull request by adiux**
Fixes a problem for HTML email and landing pages where there is no `DOCTYPE` present in the theme or saved custom HTML.

The string `null` will be injected at the beginning of the custom_html field and after the body.
This 'null' will make the email uneditable as it throws a JS error. 

There is another problem that no `<html>` tags are inserted for HTML emails and landing pages at the beginning and at the end. This PR fixes that too.

It can also be seen in code edit mode:
image

This can only be tested in combination with the plugin.

Create a theme that does not have a `DOCTYPE` in its .html file, or remove it manually from the databases `custom_html`field.

With the PR there should not be any `null` and the `<html>` tag is placed properly at the beginning and at the end.
image

### CODE REVIEW

**Comment by adiux** [comment]
As a reference, here is how to test a preset PR https://github.com/mautic/grapesjs-preset-mautic#how-to-test-a-preset-pull-request

**Comment by RCheesley** [comment]
@adiux is this still needing review? If so let's try to get these all tagged for attention in the Community Sprint for the 4.3 release at the end of June?

**Comment by jos0405** [comment]
This works!
The custom_html in emails doesn't contain the 'null' anymore.

**Review by jos0405 — APPROVED** [review]

**Comment by RCheesley** [comment]
@adiux could you address the conflicting file here? If we can get this addressed and we're still OK with it afterwards I suggest we get it merged. Is a companion PR needed for mautic/mautic on this one?

**Comment by adiux** [comment]
@RCheesley I fixed the conflicts. No, there is no companion PR as this fix is only in the preset.

**Comment by RCheesley** [comment]
LGTM based on the +1 from @jos0405 🚀

**Pull request merged**
