### PR TITLE
Duplicated Dynamic Content token in GrapesJS email builder

### PR DESCRIPTION
**Pull request by irfanhanfi**
This PR is to solve the issue raised here - https://github.com/mautic/mautic/issues/11291

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Review by ekkeguembel — APPROVED** [review]
Functional test successful - dynamic content finally works with grapesjs!

**Comment by escopecz** [comment]
Please rebase on the 5.x branch. If you want this bug fix to end up also in the next Mautic 4 release then create a duplicate PR on the 4.4 branch.

**Comment by RCheesley** [comment]
@escopecz in this repo we don't have the same branches that are used in mautic/mautic as this is the GrapesJS Preset.

That being said, in the past we have created a companion PR in mautic/mautic with the changes from the preset as that makes it much easier to test the PR in context without having to build the preset etc. @adiux do we still want to do this, and if so, do we have this documented anywhere? If not, it would make sense to do so I think?

Thanks for testing @ekkeguembel!

**Review by escopecz — APPROVED** [review]
Oops, I must admit I did not notice that this notification came from a different repo. The code change looks OK. I let someone who knows this repo hit the merge button.

**Review by volha-pivavarchyk — APPROVED** [review]
Works well

**Comment by RCheesley** [comment]
@all-contributors please add @irfanhanfi for code

**Comment by RCheesley** [comment]
@all-contributors please add @ekkeguembel for userTesting

**Comment by RCheesley** [comment]
https://github.com/all-contributors please add @escopecz for Review

**Comment by RCheesley** [comment]
@all-contributors please add @escopecz for Review

**Comment by RCheesley** [comment]
@all-contributors please add @volha-pivavarchyk for userTesting

**Pull request merged**
