### PR TITLE
DC block restored for mjml emails

### PR DESCRIPTION
**Pull request by annamunk**
Solution of the issue #11290 - Dynamic Content block missing in MJML email in GrapesJS builder in Mautic. Changes introduced by PR #26 were restored. Additionally, unnecessary duplicate script files in the dist folder have been removed.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @annamunk 🙌

**Review by patrykgruszka — COMMENTED** [review]
This PR updates dist files from source. LGTM 👍

**Comment by RCheesley** [comment]
@all-contributors please add @annamunk for code

**Comment by RCheesley** [comment]
@all-contributors please add @patrykgruszka for review

**Pull request merged**
