### PR TITLE
Add new blocks to GrapesJS builder

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
#### Description:
Add additional blocks to the grapesjs builder for mjml emails.

The new blocks are:
1. `sect 37` the section with 2 cells inside: 30% and 70%
2. `text-sect` the block with 2 text components, respectively for the heading and paragraph
3. `grid-items` the block of 2 components in row
4. `list-items` the list of 2 components

Related to the PR [#11006](https://github.com/mautic/mautic/pull/11006)

#### Steps to test:
1. Create new mjml email or choose an existing one
2. Open the grapesjs builder
3. New blocks here

### CODE REVIEW

**Comment by RCheesley** [comment]
@volha-pivavarchyk could you take a look at the conflict please? Many thanks!

**Comment by LordRembo** [comment]
I also have 2 PR's for updating GrapesJS in M5 and M4, these also fix the extra blocks in M4 too.

* one for the preset: https://github.com/mautic/grapesjs-preset-mautic/pull/49
* one Mautic (references the updated preset): https://github.com/mautic/mautic/pull/13283

For M4, there's equivalent PR's linked from those M5 PR's

**Comment by LordRembo** [comment]
Ideally, we merge those updates and can close this one.

**Comment by LordRembo** [comment]
Ah, even better, looks like the addition of the blocks is already in the latest version of this preset. Probably via another PR?
@volha-pivavarchyk could you perhaps pull in the main or 5.x branch and confirm that this is the case?
Then we can close this PR

**Comment by volha-pivavarchyk** [comment]
@LordRembo sure I'll check. But I can do it only at the weekend.

**Comment by volha-pivavarchyk** [comment]
@LordRembo In fact, these changes have already been added. This PR can be closed

**Comment by volha-pivavarchyk** [comment]
The changes have been added

**Pull request closed without merging**
